export const MOVIES = [
  "Interstellar",
  "Parasite",
  "Fight Club",
  "Barbie",
  "Sinners",
  "La La Land",
  "Whiplash",
  "The Truman Show",
  "Pulp Fiction",
  "Everything Everywhere All At Once",
  "Dead Poets Society",
  "Oppenheimer",
  "Eternal Sunshine of the Spotless Mind",
  "The Substance",
  "Get Out",
  "Dune Part One",
  "10 Things I Hate About You",
  "Spider-Man: Into The Spider-Verse",
  "The Dark Knight",
  "Joker",
  "Inception",
  "Midsommar",
  "American Psycho",
  "The Batman",
  "Knives Out",
  "The Wolf of Wall Street",
  "Dune Part Two",
  "Spirited Away",
  "Seven",
  "Spider-Man: Across The Spider-Verse",
  "Superman",
  "Forrest Gump",
  "The Grand Budapest Hotel",
  "Good Will Hunting",
  "Black Swan",
  "Marty Supreme",
  "Inglourious Basterds",
  "Kill Bill Vol 1",
  "The Perks Of Being A Wallflower",
  "Challengers",
  "The Silence Of The Lambs",
  "The Shining",
  "Project Hail Mary",
  "500 Days of Summer",
  "Weapons",
  "Lady Bird",
  "Saltburn",
  "Shutter Island",
  "Call Me By Your Name",
  "Nosferatu",
  "One Battle After Another",
  "Little Women",
  "Poor Things",
  "The Godfather",
  "Gone Girl",
  "Frankenstein",
  "Ratatouille",
  "Fantastic Mr. Fox",
  "Spider-Man No Way Home",
  "The Menu",
  "Once Upon A Time In Hollywood",
  "Wicked",
  "Anora",
  "Django Unchained",
  "Avengers Infinity War",
  "The Shawshank Redemption",
  "Avengers Endgame",
  "The Devil Wears Prada",
  "The Lord of the Rings: The Fellowship of the Ring",
  "Mean Girls",
  "The Matrix",
  "Baby Driver",
  "Taxi Driver",
  "Titanic",
  "Coraline",
  "Little Miss Sunshine",
  "Donnie Darko",
  "The Hunger Games",
  "The Notebook",
  "Deadpool & Wolverine",
  "Hereditary",
  "Mickey 17",
  "Scott Pilgrim vs. the World",
  "Harry Potter and The Prisoner of Azkaban",
  "The Social Network",
  "Glass Onion",
  "Harry Potter and The Sorcerer's Stone",
  "Inside Out 2",
  "Coco",
  "Inside Out",
  "Her",
  "Howl's Moving Castle",
  "Back To The Future",
  "Arrival",
  "Pride & Prejudice",
  "Avatar",
  "Wake Up Dead Man",
  "Guardians of the Galaxy",
  "GoodFellas",
  "Up",
  "The Good The Bad and The Ugly",
  "Rear Window",
  "Star Wars Episode V",
  "Star Wars Episode IV",
  "2001: A Space Odyssey",
  "Apocalypse Now",
  "Mulholland Drive",
  "There Will Be Blood",
  "No Country For Old Men",
  "Mad Max: Fury Road",
  "Blade Runner 2049",
  "Moonlight",
  "Portrait of a Lady on Fire",
  "Raging Bull",
  "Vertigo",
  "Psycho",
  "North by Northwest",
  "Prisoners",
  "A Clockwork Orange",
  "Full Metal Jacket",
  "The Lighthouse",
  "Nightcrawler",
  "Drive",
  "Pan's Labyrinth",
  "Aftersun",
  "X",
  "Pearl",
  "Nope",
  "Us",
  "It",
  "Scream",
  "All Quiet On The Western Front",
  "Cast Away",
  "Saving Private Ryan",
  "Casablanca",
  "Wall E",
  "Jaws",
  "Jurassic Park",
  "The Usual Suspects",
  "Network",
  "12 Angry Men",
  "The Godfather Part II",
  "The Godfather Part III",
  "Schindler's List",
  "The Green Mile",
  "Catch Me If You Can",
  "Batman Begins",
  "The Dark Knight Rises",
  "The Lord of the Rings: The Two Towers",
  "The Lord of the Rings: The Return of the King",
  "Return of the Jedi",
  "Star Wars Episode I",
  "Star Wars Episode II",
  "Star Wars Epsiode III",
  "Raiders of the Lost Ark",
  "The Temple of Doom",
  "Indiana Jones",
];
